# 1. First Steps with Julia

Some basic usage of Julia.

## Basics

In [21]:
# Check Julia is available
versioninfo()

Julia Version 1.10.0
Commit 3120989f39b (2023-12-25 18:01 UTC)
Build Info:
  Official https://julialang.org/ release
Platform Info:
  OS: Linux (x86_64-linux-gnu)
  CPU: 8 × 11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-15.0.7 (ORCJIT, tigerlake)
  Threads: 2 on 8 virtual cores


In [22]:
# Function definition
function f(x, y)
    x + y
end

f (generic function with 1 method)

In [23]:
f(4, 3)

7

In [24]:
# Compact function definition
g(x, y) = x - y
g(3, 4)

-1

In [25]:
# Vectors and matrices
v = [1, 2, 3]

3-element Vector{Int64}:
 1
 2
 3

In [26]:
# Vector from for loop
v3 = [3x for x in 1:9]

9-element Vector{Int64}:
  3
  6
  9
 12
 15
 18
 21
 24
 27

In [27]:
# Latex-like syntax for maths symbols
# \sqrt + tab to produce square root
v_4 = [√(x₁) for x₁ ∈ 1:9]

9-element Vector{Float64}:
 1.0
 1.4142135623730951
 1.7320508075688772
 2.0
 2.23606797749979
 2.449489742783178
 2.6457513110645907
 2.8284271247461903
 3.0

In [28]:
# Append to vector
c = []
append!(c, 5)

1-element Vector{Any}:
 5

In [29]:
# Fractions
x = 1 // 2 + 1 // 4

3//4

In [30]:
typeof(x)

Rational{Int64}

## Data types

## Tuples

In [31]:
# Tuple
a = (1, 2)

(1, 2)

In [32]:
# Convert collection (like an iterator) into array
v = collect(3:10)
v[7:end]

2-element Vector{Int64}:
  9
 10

## Matrices

In [33]:
# Print expression and result
@show zeros(5)

zeros(5) = [0.0, 0.0, 0.0, 0.0, 0.0]


5-element Vector{Float64}:
 0.0
 0.0
 0.0
 0.0
 0.0

In [34]:
x = reshape(1:12, 3, 4)

3×4 reshape(::UnitRange{Int64}, 3, 4) with eltype Int64:
 1  4  7  10
 2  5  8  11
 3  6  9  12

In [35]:
m = zeros(4, 5)
m[1, 3] = 66.0
# Arrays indexed at 1
m

4×5 Matrix{Float64}:
 0.0  0.0  66.0  0.0  0.0
 0.0  0.0   0.0  0.0  0.0
 0.0  0.0   0.0  0.0  0.0
 0.0  0.0   0.0  0.0  0.0

## Data structures

In [36]:
mutable struct Point1
    x::Int
    y::Float64
    meta
end
p = Point1(0, 0.0, "Origin")
dump(p)

Point1
  x: Int64 0
  y: Float64 0.0
  meta: String "Origin"


In [37]:
# Struct with defaults
Base.@kwdef struct Point2
    x::Int64 = 1
    y::Float64 = 2.0
    meta
end
p2 = Point2(x=999, meta="Origin")

Point2(999, 2.0, "Origin")

In [38]:
try
    p2.x = 3333
catch e
    println(e)
end

ErrorException("setfield!: immutable struct of type Point2 cannot be changed")


In [39]:
# Mutable struct with defaults
using Parameters
@with_kw mutable struct Point3
    x::Int64 = 1
    y::Float64 = 2.0
    meta
end
p3 = Point3(x=999, meta="Origin")
p3.x = 66
p3

Point3
  x: Int64 66
  y: Float64 2.0
  meta: String "Origin"


## Dictionaries

In [40]:
x = Dict{Int,Float64}()
x[5] = 66.06
x[7] = 99
x

Dict{Int64, Float64} with 2 entries:
  5 => 66.06
  7 => 99.0

In [41]:
y = Dict(1 => 5.5, 2 => 4.5)

Dict{Int64, Float64} with 2 entries:
  2 => 4.5
  1 => 5.5

## Text processing

In [42]:
x = 123
"$x + 3 = $(x+3)"

"123 + 3 = 126"

## Functions

In [43]:
function g(x::Int, y::Int) # limit arg type
    return y, x # tuple returned
end

g(x::Int, y::Bool) = x * y # multiple dispatch
methods(g)

# 3 methods for generic function "g" from Main:
 [1] g(x::Int64, y::Bool)
     @ In[43]:5
 [2] g(x::Int64, y::Int64)
     @ In[43]:1
 [3] g(x, y)
     @ In[24]:2

## Operators

In [44]:
# Vecotrisation via dot operator
@show [1 2] .< [2 1]

[1 2] .< [2 1] = Bool[1 0]


1×2 BitMatrix:
 1  0

In [45]:
x = [1 2 3] # matrix (1x3)
y = [1, 2, 3] # vector (3) (column)
@show x .+ y # dimension broadcasting
@show x + y' # transpose
@show x * y; # array multiplication

x .+ y = [2 3 4; 3 4 5; 4 5 6]
x + y' = [2 4 6]
x * y = [14]


1-element Vector{Int64}:
 14

In [46]:
f(x, y) = x < y ? x : y
a = [1, 2, 3]
b = [0, 5, 6]
f.(a, b)

3-element Vector{Int64}:
 0
 2
 3

## Simple demo

In [47]:
# Approximate pi
function calc_pi(n, T)
    # n is number of replications
    # T is result type
    s = one(T)
    f = one(T)
    for i::T in 1:n
        f *= i / (2i + 1)
        s += f
    end
    2s
end

calc_pi(10000, BigFloat) - π

1.036340226611333355046362223536047948533920043732353766202844416420231016379491e-76

In [48]:
[calc_pi(n, Rational) for n in 1:20]

20-element Vector{Rational{Int64}}:
                8//3
               44//15
               64//21
              976//315
            10816//3465
           141088//45045
            47104//15015
          2404096//765765
         45693952//14549535
         45701632//14549535
         80863232//25741485
       5256312832//1673196525
       3153846272//1003917915
     457311809536//145568097675
     833925152768//265447707525
    4725585805312//1504203675975
   14176771899392//4512611027925
  524540820979712//166966608033225
  104908189597696//33393321606645
 4301236281540608//1369126185872445

## Integration with other programming languages

In [54]:
using PyCall
np = pyimport("numpy")
a = np.zeros((4, 5))

4×5 Matrix{Float64}:
 0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0

In [55]:
a[1, 1] = 5
np.mean(a)

0.25